// Turning an uploaded PROS project into compiler inputs.

import type { PchVariant } from './flags.ts';

export type ProjectFiles = Record<string, string | Uint8Array>;

export interface PreparedProject {
  /** Translation units (project-relative paths). */
  sources: string[];
  /** Everything mounted under /project (headers, sources), already filtered. */
  files: Record<string, string>;
  /** Generated C source that embeds static/ assets (LemLib ASSET()). */
  assetSource: string | null;
  pch: PchVariant;
  /** Libraries the project includes; only their objects (and global constructors) are linked. */
  uses: { lemlib: boolean; ez: boolean };
  notes: ProjectNote[];
}

export interface ProjectNote {
  level: 'info' | 'warning' | 'error';
  message: string;
}

const dec = new TextDecoder();
const asText = (d: string | Uint8Array) => (typeof d === 'string' ? d : dec.decode(d));

/** Library headers the simulator provides; project copies are ignored so ours are used. */
const SHADOWED = [
  /^include\/api\.h$/,
  /^include\/pros\//,
  /^include\/lemlib\//,
  /^include\/fmt\//,
  /^include\/EZ-Template\//,
  /^include\/okapi\//,
  /^include\/liblvgl\//,
];
const IGNORED = [/^firmware\//, /^bin\//, /^\.d\//, /^\.vscode\//, /^\.git\//, /(^|\/)\.DS_Store$/, /\.(o|a|d|elf|bin)$/];
const SOURCE_RE = /^src\/.+\.(c|cc|cpp|cxx)$/;
const HEADER_RE = /\.(h|hh|hpp|hxx|inc|ipp)$/;

/** If a zip wraps the project in a single top folder, strip it. */
export function normalizeRoot(files: ProjectFiles): ProjectFiles {
  const paths = Object.keys(files).map((p) => p.replaceAll('\\', '/').replace(/^\.?\//, ''));
  const tops = new Set(paths.map((p) => p.split('/')[0]));
  const hasMarkers = paths.some((p) => p === 'project.pros' || p.startsWith('src/'));
  if (!hasMarkers && tops.size === 1) {
    const top = [...tops][0] + '/';
    return Object.fromEntries(Object.entries(files).map(([p, d]) => [p.replaceAll('\\', '/').replace(/^\.?\//, '').slice(top.length), d]));
  }
  return Object.fromEntries(Object.entries(files).map(([p, d]) => [p.replaceAll('\\', '/').replace(/^\.?\//, ''), d]));
}

/** Symbol stem objcopy would use for a static/ file: static/path.txt -> static_path_txt. */
export const assetSymbol = (p: string) => '_binary_' + p.replace(/[^A-Za-z0-9]/g, '_');

function assetSourceFor(assets: Array<[string, Uint8Array]>): string {
  let out = '// Generated by the simulator: embeds static/ files for LemLib ASSET().\n#include <stddef.h>\n#include <stdint.h>\n';
  for (const [p, data] of assets) {
    const sym = assetSymbol(p);
    const bytes = Array.from(data, (b) => b.toString()).join(',');
    out += `uint8_t ${sym}_start[] = {${bytes}${data.length ? ',' : ''}0};\n`;
    out += `const size_t ${sym}_len = ${data.length};\n`;
  }
  return out;
}

function versionNotes(projectPros: string | undefined, libraries: Record<string, string>): ProjectNote[] {
  if (!projectPros) return [];
  const notes: ProjectNote[] = [];
  try {
    const json = JSON.parse(projectPros);
    const templates = json?.['py/state']?.templates ?? json?.templates ?? {};
    for (const [name, t] of Object.entries<Record<string, unknown>>(templates)) {
      const want = libraries[name];
      const have = String((t as { version?: unknown })?.version ?? '');
      if (!want || !have) continue;
      const mm = (v: string) => v.split('.').slice(0, 2).join('.');
      if (mm(have) !== mm(want)) {
        notes.push({ level: 'warning', message: `Project uses ${name} ${have}; the simulator implements ${name} ${want}. Calls that changed between versions may not compile.` });
      }
    }
  } catch {
    // project.pros is not JSON in some older projects; ignore.
  }
  return notes;
}

export function prepareProject(input: ProjectFiles, libraries: Record<string, string>): PreparedProject {
  const files: Record<string, string> = {};
  const sources: string[] = [];
  const assets: Array<[string, Uint8Array]> = [];
  const notes: ProjectNote[] = [];
  let shadowed = 0;
  for (const [path, data] of Object.entries(normalizeRoot(input))) {
    if (!path || IGNORED.some((r) => r.test(path))) continue;
    if (path.startsWith('static/')) {
      assets.push([path, typeof data === 'string' ? new TextEncoder().encode(data) : data]);
      continue;
    }
    if (SHADOWED.some((r) => r.test(path))) {
      shadowed++;
      continue;
    }
    if (SOURCE_RE.test(path)) {
      sources.push(path);
      files[path] = asText(data);
    } else if (HEADER_RE.test(path) || path.startsWith('include/') || path.startsWith('src/')) {
      files[path] = asText(data);
    }
  }
  sources.sort();
  if (!sources.length) notes.push({ level: 'error', message: 'No source files found. Expected .cpp files under src/.' });
  if (shadowed) notes.push({ level: 'info', message: `Using the simulator's PROS / LemLib / EZ-Template headers instead of ${shadowed} bundled copies in include/.` });

  const allText = Object.values(files).join('\n');
  const usesEz = /#\s*include\s*[<"]EZ-Template\//.test(allText);
  const usesLemlib = /#\s*include\s*[<"]lemlib\//.test(allText);
  if (/#\s*include\s*[<"]liblvgl\/(?!llemu\.h)/.test(allText)) {
    notes.push({ level: 'warning', message: 'liblvgl (LVGL graphics) is not available in the simulator; code that draws on the brain screen will not compile.' });
  }
  notes.push(...versionNotes(asText(input['project.pros'] ?? ''), libraries));
  return {
    sources,
    files,
    assetSource: assets.length ? assetSourceFor(assets) : null,
    pch: usesEz ? 'ez' : 'lemlib',
    uses: { lemlib: usesLemlib, ez: usesEz },
    notes,
  };
}
