// Generate docs/supported-api.md from the code: which PROS C functions the runtime
// simulates vs. which exist in the PROS headers but are not simulated.
//   node scripts/gen-supported-api.ts
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { ShimManifest } from '../src/compiler/bundle.ts';
import { simulatedEnvNames } from '../src/sim/pros-api.ts';
import { repoRoot } from './node-toolchain.ts';

const manifest = JSON.parse(await readFile(path.join(repoRoot, 'public/sim/manifest.json'), 'utf8')) as ShimManifest;
const simulated = new Set(simulatedEnvNames());
const known = manifest.knownCApi.filter((n) => !/^(lcd_|screen_)/.test(n));

const groups: Array<[string, RegExp]> = [
  ['Tasks, timing and mutexes (`pros::Task`, `pros::delay`, `pros::Mutex`)', /^(millis|micros|delay|task_|mutex_|rtos_|sem_|queue_)/],
  ['Motors (`pros::Motor`, `pros::MotorGroup`)', /^motor_/],
  ['Inertial sensor (`pros::Imu`)', /^imu_/],
  ['Rotation sensor (`pros::Rotation`)', /^rotation_/],
  ['Distance sensor (`pros::Distance`)', /^distance_/],
  ['3-wire ports (`pros::adi::*`)', /^(ext_)?adi_/],
  ['Controller, competition and battery', /^(controller_|competition_|battery_|usd_)/],
  ['Optical sensor', /^optical_/],
  ['GPS sensor', /^gps_/],
  ['Vision / AI Vision sensors', /^(vision_|aivision_)/],
  ['Radio link and generic serial', /^(link_|serial_)/],
  ['Device registry and kernel', /^(registry_|get_plugged|enable_banner|serctl|fdctl|port_mutex)/],
];

let md = `# Supported API

What user code can call in the simulator. Generated by \`scripts/gen-supported-api.ts\`
from the simulator's source; the PROS lists are exact.

- **Simulated** calls behave like on a robot, using the robot profile.
- **Not simulated** calls compile and run, but do nothing (they return 0) and the
  simulator shows a one-time note, e.g. "optical_get_hue() is not supported by the simulator yet".
- Calls to functions that exist in no library are build errors, like on a real robot.

Versions: PROS kernel ${manifest.libraries.kernel}, LemLib ${manifest.libraries.LemLib}, EZ-Template ${manifest.libraries['EZ-Template']}.
The real public headers of these versions are used, so every signature matches.

## PROS

The C++ classes (\`pros::Motor\`, \`pros::MotorGroup\`, \`pros::Imu\`, \`pros::Task\`, \`pros::adi::Pneumatics\`, ...)
are PROS's own code, compiled unmodified; they call the C functions below.

`;
const covered = new Set<string>();
for (const [title, re] of groups) {
  const names = [...new Set([...known.filter((n) => re.test(n)), ...[...simulated].filter((n) => re.test(n))])].sort();
  if (!names.length) continue;
  names.forEach((n) => covered.add(n));
  const sim = names.filter((n) => simulated.has(n));
  const not = names.filter((n) => !simulated.has(n));
  md += `### ${title}\n\n`;
  md += `**Simulated (${sim.length}):** ${sim.length ? sim.map((n) => '`' + n + '`').join(', ') : 'none yet'}\n\n`;
  if (not.length) md += `**Not simulated (${not.length}):** ${not.map((n) => '`' + n + '`').join(', ')}\n\n`;
}
const rest = known.filter((n) => !covered.has(n)).sort();
if (rest.length) md += `### Other\n\n**Not simulated:** ${rest.map((n) => '`' + n + '`').join(', ')}\n\n`;

md += `### Model notes

- **Motors:** speed follows the cartridge in the robot profile; the code's gearset setting scales encoder degrees and rpm like a real V5 motor (raw counts are physical ticks, the firmware default units). Brake modes: hold/brake stop at the drivetrain's full deceleration, coast at half. Temperature, power, torque and current are plausible constants.
- **Drivetrain:** idealized tank kinematics limited by the profile's top speed and acceleration; walls stop the robot (wheels slip, encoders keep counting).
- **IMU:** calibration takes 2 s; heading/rotation follow the robot exactly; the accelerometer reports real acceleration plus vibration while moving.
- **Rotation sensors:** profile entries with \`trackingWheel\` read the wheel's travel; with \`mechanism\` they read that mechanism's angle.
- **Distance sensors:** measure to the field perimeter along the mounted direction.
- **3-wire digital outputs:** drive pneumatic mechanisms in the profile (\`adi_digital_out\` devices).
- **LLEMU (\`pros::lcd\`):** shown in the Brain screen panel. Other brain-screen drawing (\`pros::screen\`) is ignored silently.
- **Controller:** always connected, all inputs zero (autonomous only).

## LemLib ${manifest.libraries.LemLib}

Built from LemLib's own source except odometry and motions, which are re-implemented as idealized motion (no PID is simulated; all PID / exit-condition / slew settings are accepted and ignored). Odometry is ideal: \`getPose()\` is the robot's true pose in the frame set by \`setPose()\`.

| API | Status |
| --- | --- |
| \`Drivetrain\`, \`ControllerSettings\`, \`OdomSensors\`, \`TrackingWheel\`, drive curves, \`Pose\`, \`PID\`, \`ExitCondition\`, \`Timer\`, utilities, logger | Real LemLib code |
| \`Chassis::calibrate\`, \`setPose\`, \`getPose\`, \`resetLocalPosition\`, \`setBrakeMode\` | Supported |
| \`moveToPoint\`, \`moveToPose\` (boomerang lead), \`turnToHeading\`, \`turnToPoint\`, \`swingToHeading\`, \`swingToPoint\` | Supported: \`forwards\`, \`direction\`, \`maxSpeed\`, \`minSpeed\` + \`earlyExitRange\` (motion chaining), \`lead\`, timeouts, \`async\` |
| \`follow\` (pure pursuit on \`ASSET()\` paths from \`static/\`) | Supported (path.jerryio / LemLib format) |
| \`waitUntil\`, \`waitUntilDone\`, \`cancelMotion\`, \`cancelAllMotions\`, \`isInMotion\` | Supported, with LemLib's queueing semantics |
| \`tank\`, \`arcade\`, \`curvature\` | Real LemLib code (driver control is not simulated yet) |
| \`lemlib::getSpeed\`, \`getLocalSpeed\`, \`estimatePose\` | Supported (ideal) |

## EZ-Template ${manifest.libraries['EZ-Template']}

Built from EZ-Template's own source, including its odometry, target bookkeeping, auton selector and exit conditions (\`pid_wait\`, \`pid_wait_until\`, ... behave as on a robot). Only the PID motor-control loop is replaced: each motion's target is driven with idealized motion.

| API | Status |
| --- | --- |
| \`pid_drive_set\` (incl. heading hold) | Supported |
| \`pid_turn_set\`, \`pid_turn_relative_set\`, turn behaviors | Supported |
| \`pid_swing_set\` (incl. opposite-side speed), \`pid_swing_relative_set\` | Supported |
| \`pid_odom_set\` (point-to-point, pure pursuit, boomerang, injected paths), \`odom_*\` getters/setters | Supported |
| \`pid_wait\`, \`pid_wait_until\`, \`pid_wait_quick\`, \`pid_wait_quick_chain\`, \`pid_wait_until_index\`, \`interfered\` | Real EZ-Template code |
| PID / slew / exit-condition / chain constants, \`pid_tuner_*\`, auton selector, SD card | Accepted (PID constants ignored; SD card absent) |
| \`opcontrol_*\` | Real EZ-Template code (driver control is not simulated yet) |

## Not supported yet

- Driver control (\`opcontrol()\` never runs; the controller reads zero).
- Holonomic / X-drive drivetrains (profiles are tank only).
- Game objects and scoring (coming with game-specific fields).
- liblvgl graphics beyond LLEMU, file I/O on the SD card, radio/serial.
`;

await writeFile(path.join(repoRoot, 'docs/supported-api.md'), md);
console.log(`wrote docs/supported-api.md: ${simulated.size} simulated, ${known.filter((n) => !simulated.has(n)).length} known-but-not-simulated`);
